// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { SignatureDescriptor } from "./SignatureDescriptor";

export class SignatureDescriptors {
  static encode(message: SignatureDescriptors, writer: Writer): void {
    const signatures = message.signatures;
    for (let i: i32 = 0; i < signatures.length; ++i) {
      writer.uint32(10);
      writer.fork();
      SignatureDescriptor.encode(signatures[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SignatureDescriptors {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SignatureDescriptors();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signatures.push(
            SignatureDescriptor.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signatures: Array<SignatureDescriptor>;

  constructor(signatures: Array<SignatureDescriptor> = []) {
    this.signatures = signatures;
  }
}
