// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

export enum SignMode {
  SIGN_MODE_UNSPECIFIED = 0,
  SIGN_MODE_DIRECT = 1,
  SIGN_MODE_TEXTUAL = 2,
  SIGN_MODE_DIRECT_AUX = 3,
  SIGN_MODE_LEGACY_AMINO_JSON = 127,
  SIGN_MODE_EIP_191 = 191,
}
