// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class BatchContractDeregistrationProposal {
  static encode(
    message: BatchContractDeregistrationProposal,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.title);

    writer.uint32(18);
    writer.string(message.description);

    const contracts = message.contracts;
    if (contracts.length !== 0) {
      for (let i: i32 = 0; i < contracts.length; ++i) {
        writer.uint32(26);
        writer.string(contracts[i]);
      }
    }
  }

  static decode(
    reader: Reader,
    length: i32
  ): BatchContractDeregistrationProposal {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BatchContractDeregistrationProposal();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.title = reader.string();
          break;

        case 2:
          message.description = reader.string();
          break;

        case 3:
          message.contracts.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  title: string;
  description: string;
  contracts: Array<string>;

  constructor(
    title: string = "",
    description: string = "",
    contracts: Array<string> = []
  ) {
    this.title = title;
    this.description = description;
    this.contracts = contracts;
  }
}
