// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { ContractRegistrationRequest } from "./ContractRegistrationRequest";

export class BatchContractRegistrationRequestProposal {
  static encode(
    message: BatchContractRegistrationRequestProposal,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.title);

    writer.uint32(18);
    writer.string(message.description);

    const contractRegistrationRequests = message.contractRegistrationRequests;
    for (let i: i32 = 0; i < contractRegistrationRequests.length; ++i) {
      writer.uint32(26);
      writer.fork();
      ContractRegistrationRequest.encode(
        contractRegistrationRequests[i],
        writer
      );
      writer.ldelim();
    }
  }

  static decode(
    reader: Reader,
    length: i32
  ): BatchContractRegistrationRequestProposal {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BatchContractRegistrationRequestProposal();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.title = reader.string();
          break;

        case 2:
          message.description = reader.string();
          break;

        case 3:
          message.contractRegistrationRequests.push(
            ContractRegistrationRequest.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  title: string;
  description: string;
  contractRegistrationRequests: Array<ContractRegistrationRequest>;

  constructor(
    title: string = "",
    description: string = "",
    contractRegistrationRequests: Array<ContractRegistrationRequest> = []
  ) {
    this.title = title;
    this.description = description;
    this.contractRegistrationRequests = contractRegistrationRequests;
  }
}
