// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { StoreCodeProposal } from "../../../cosmwasm/wasm/v1/StoreCodeProposal";

export class BatchStoreCodeProposal {
  static encode(message: BatchStoreCodeProposal, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.title);

    writer.uint32(18);
    writer.string(message.description);

    const proposals = message.proposals;
    for (let i: i32 = 0; i < proposals.length; ++i) {
      writer.uint32(26);
      writer.fork();
      StoreCodeProposal.encode(proposals[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): BatchStoreCodeProposal {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BatchStoreCodeProposal();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.title = reader.string();
          break;

        case 2:
          message.description = reader.string();
          break;

        case 3:
          message.proposals.push(
            StoreCodeProposal.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  title: string;
  description: string;
  proposals: Array<StoreCodeProposal>;

  constructor(
    title: string = "",
    description: string = "",
    proposals: Array<StoreCodeProposal> = []
  ) {
    this.title = title;
    this.description = description;
    this.proposals = proposals;
  }
}
