// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgDeactivateContract {
  static encode(message: MsgDeactivateContract, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    writer.uint32(18);
    writer.string(message.contractAddress);
  }

  static decode(reader: Reader, length: i32): MsgDeactivateContract {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgDeactivateContract();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.contractAddress = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  contractAddress: string;

  constructor(sender: string = "", contractAddress: string = "") {
    this.sender = sender;
    this.contractAddress = contractAddress;
  }
}
