// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { ContractRegistrationRequest } from "./ContractRegistrationRequest";

export class MsgRegisterContract {
  static encode(message: MsgRegisterContract, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    const contractRegistrationRequest = message.contractRegistrationRequest;
    if (contractRegistrationRequest !== null) {
      writer.uint32(18);
      writer.fork();
      ContractRegistrationRequest.encode(contractRegistrationRequest, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgRegisterContract {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgRegisterContract();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.contractRegistrationRequest =
            ContractRegistrationRequest.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  contractRegistrationRequest: ContractRegistrationRequest | null;

  constructor(
    sender: string = "",
    contractRegistrationRequest: ContractRegistrationRequest | null = null
  ) {
    this.sender = sender;
    this.contractRegistrationRequest = contractRegistrationRequest;
  }
}
