// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { FundingMode } from "./FundingMode";

export class RegisteredContract {
  static encode(message: RegisteredContract, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.gasLimit);

    writer.uint32(16);
    writer.uint64(message.gasPrice);

    writer.uint32(24);
    writer.bool(message.isExecutable);

    writer.uint32(32);
    writer.uint64(message.codeId);

    writer.uint32(42);
    writer.string(message.adminAddress);

    writer.uint32(50);
    writer.string(message.granterAddress);

    writer.uint32(56);
    writer.int32(message.fundMode);
  }

  static decode(reader: Reader, length: i32): RegisteredContract {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RegisteredContract();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.gasLimit = reader.uint64();
          break;

        case 2:
          message.gasPrice = reader.uint64();
          break;

        case 3:
          message.isExecutable = reader.bool();
          break;

        case 4:
          message.codeId = reader.uint64();
          break;

        case 5:
          message.adminAddress = reader.string();
          break;

        case 6:
          message.granterAddress = reader.string();
          break;

        case 7:
          message.fundMode = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  gasLimit: u64;
  gasPrice: u64;
  isExecutable: bool;
  codeId: u64;
  adminAddress: string;
  granterAddress: string;
  fundMode: FundingMode;

  constructor(
    gasLimit: u64 = 0,
    gasPrice: u64 = 0,
    isExecutable: bool = false,
    codeId: u64 = 0,
    adminAddress: string = "",
    granterAddress: string = "",
    fundMode: FundingMode = 0
  ) {
    this.gasLimit = gasLimit;
    this.gasPrice = gasPrice;
    this.isExecutable = isExecutable;
    this.codeId = codeId;
    this.adminAddress = adminAddress;
    this.granterAddress = granterAddress;
    this.fundMode = fundMode;
  }
}
