// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Any } from "../../../google/protobuf/Any";
import { ModeInfo } from "./ModeInfo";

export class SignerInfo {
  static encode(message: SignerInfo, writer: Writer): void {
    const publicKey = message.publicKey;
    if (publicKey !== null) {
      writer.uint32(10);
      writer.fork();
      Any.encode(publicKey, writer);
      writer.ldelim();
    }

    const modeInfo = message.modeInfo;
    if (modeInfo !== null) {
      writer.uint32(18);
      writer.fork();
      ModeInfo.encode(modeInfo, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.uint64(message.sequence);
  }

  static decode(reader: Reader, length: i32): SignerInfo {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SignerInfo();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.publicKey = Any.decode(reader, reader.uint32());
          break;

        case 2:
          message.modeInfo = ModeInfo.decode(reader, reader.uint32());
          break;

        case 3:
          message.sequence = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  publicKey: Any | null;
  modeInfo: ModeInfo | null;
  sequence: u64;

  constructor(
    publicKey: Any | null = null,
    modeInfo: ModeInfo | null = null,
    sequence: u64 = 0
  ) {
    this.publicKey = publicKey;
    this.modeInfo = modeInfo;
    this.sequence = sequence;
  }
}
