// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Coin } from "../../base/v1beta1/Coin";

export class Tip {
  static encode(message: Tip, writer: Writer): void {
    const amount = message.amount;
    for (let i: i32 = 0; i < amount.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Coin.encode(amount[i], writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.string(message.tipper);
  }

  static decode(reader: Reader, length: i32): Tip {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Tip();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.amount.push(Coin.decode(reader, reader.uint32()));
          break;

        case 2:
          message.tipper = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  amount: Array<Coin>;
  tipper: string;

  constructor(amount: Array<Coin> = [], tipper: string = "") {
    this.amount = amount;
    this.tipper = tipper;
  }
}
