// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class TxRaw {
  static encode(message: TxRaw, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.bodyBytes);

    writer.uint32(18);
    writer.bytes(message.authInfoBytes);

    const signatures = message.signatures;
    if (signatures.length !== 0) {
      for (let i: i32 = 0; i < signatures.length; ++i) {
        writer.uint32(26);
        writer.bytes(signatures[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): TxRaw {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TxRaw();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.bodyBytes = reader.bytes();
          break;

        case 2:
          message.authInfoBytes = reader.bytes();
          break;

        case 3:
          message.signatures.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  bodyBytes: Uint8Array;
  authInfoBytes: Uint8Array;
  signatures: Array<Uint8Array>;

  constructor(
    bodyBytes: Uint8Array = new Uint8Array(0),
    authInfoBytes: Uint8Array = new Uint8Array(0),
    signatures: Array<Uint8Array> = []
  ) {
    this.bodyBytes = bodyBytes;
    this.authInfoBytes = authInfoBytes;
    this.signatures = signatures;
  }
}
