// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { AccessConfig } from "./AccessConfig";

export class CodeInfo {
  static encode(message: CodeInfo, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.codeHash);

    writer.uint32(18);
    writer.string(message.creator);

    const instantiateConfig = message.instantiateConfig;
    if (instantiateConfig !== null) {
      writer.uint32(42);
      writer.fork();
      AccessConfig.encode(instantiateConfig, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CodeInfo {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CodeInfo();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.codeHash = reader.bytes();
          break;

        case 2:
          message.creator = reader.string();
          break;

        case 5:
          message.instantiateConfig = AccessConfig.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  codeHash: Uint8Array;
  creator: string;
  instantiateConfig: AccessConfig | null;

  constructor(
    codeHash: Uint8Array = new Uint8Array(0),
    creator: string = "",
    instantiateConfig: AccessConfig | null = null
  ) {
    this.codeHash = codeHash;
    this.creator = creator;
    this.instantiateConfig = instantiateConfig;
  }
}
