// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MigrateContractProposal {
  static encode(message: MigrateContractProposal, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.title);

    writer.uint32(18);
    writer.string(message.description);

    writer.uint32(34);
    writer.string(message.contract);

    writer.uint32(40);
    writer.uint64(message.codeId);

    writer.uint32(50);
    writer.bytes(message.msg);
  }

  static decode(reader: Reader, length: i32): MigrateContractProposal {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MigrateContractProposal();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.title = reader.string();
          break;

        case 2:
          message.description = reader.string();
          break;

        case 4:
          message.contract = reader.string();
          break;

        case 5:
          message.codeId = reader.uint64();
          break;

        case 6:
          message.msg = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  title: string;
  description: string;
  contract: string;
  codeId: u64;
  msg: Uint8Array;

  constructor(
    title: string = "",
    description: string = "",
    contract: string = "",
    codeId: u64 = 0,
    msg: Uint8Array = new Uint8Array(0)
  ) {
    this.title = title;
    this.description = description;
    this.contract = contract;
    this.codeId = codeId;
    this.msg = msg;
  }
}
