// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { AccessConfig } from "./AccessConfig";

export class MsgStoreAndMigrateContract {
  static encode(message: MsgStoreAndMigrateContract, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.authority);

    writer.uint32(18);
    writer.bytes(message.wasmByteCode);

    const instantiatePermission = message.instantiatePermission;
    if (instantiatePermission !== null) {
      writer.uint32(26);
      writer.fork();
      AccessConfig.encode(instantiatePermission, writer);
      writer.ldelim();
    }

    writer.uint32(34);
    writer.string(message.contract);

    writer.uint32(42);
    writer.bytes(message.msg);
  }

  static decode(reader: Reader, length: i32): MsgStoreAndMigrateContract {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgStoreAndMigrateContract();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.authority = reader.string();
          break;

        case 2:
          message.wasmByteCode = reader.bytes();
          break;

        case 3:
          message.instantiatePermission = AccessConfig.decode(
            reader,
            reader.uint32()
          );
          break;

        case 4:
          message.contract = reader.string();
          break;

        case 5:
          message.msg = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  authority: string;
  wasmByteCode: Uint8Array;
  instantiatePermission: AccessConfig | null;
  contract: string;
  msg: Uint8Array;

  constructor(
    authority: string = "",
    wasmByteCode: Uint8Array = new Uint8Array(0),
    instantiatePermission: AccessConfig | null = null,
    contract: string = "",
    msg: Uint8Array = new Uint8Array(0)
  ) {
    this.authority = authority;
    this.wasmByteCode = wasmByteCode;
    this.instantiatePermission = instantiatePermission;
    this.contract = contract;
    this.msg = msg;
  }
}
