// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { AccessConfig } from "./AccessConfig";

export class MsgStoreCode {
  static encode(message: MsgStoreCode, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    writer.uint32(18);
    writer.bytes(message.wasmByteCode);

    const instantiatePermission = message.instantiatePermission;
    if (instantiatePermission !== null) {
      writer.uint32(42);
      writer.fork();
      AccessConfig.encode(instantiatePermission, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgStoreCode {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgStoreCode();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.wasmByteCode = reader.bytes();
          break;

        case 5:
          message.instantiatePermission = AccessConfig.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  wasmByteCode: Uint8Array;
  instantiatePermission: AccessConfig | null;

  constructor(
    sender: string = "",
    wasmByteCode: Uint8Array = new Uint8Array(0),
    instantiatePermission: AccessConfig | null = null
  ) {
    this.sender = sender;
    this.wasmByteCode = wasmByteCode;
    this.instantiatePermission = instantiatePermission;
  }
}
