// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class SudoContractProposal {
  static encode(message: SudoContractProposal, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.title);

    writer.uint32(18);
    writer.string(message.description);

    writer.uint32(26);
    writer.string(message.contract);

    writer.uint32(34);
    writer.bytes(message.msg);
  }

  static decode(reader: Reader, length: i32): SudoContractProposal {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SudoContractProposal();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.title = reader.string();
          break;

        case 2:
          message.description = reader.string();
          break;

        case 3:
          message.contract = reader.string();
          break;

        case 4:
          message.msg = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  title: string;
  description: string;
  contract: string;
  msg: Uint8Array;

  constructor(
    title: string = "",
    description: string = "",
    contract: string = "",
    msg: Uint8Array = new Uint8Array(0)
  ) {
    this.title = title;
    this.description = description;
    this.contract = contract;
    this.msg = msg;
  }
}
