// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { AccessConfigUpdate } from "./AccessConfigUpdate";

export class UpdateInstantiateConfigProposal {
  static encode(
    message: UpdateInstantiateConfigProposal,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.title);

    writer.uint32(18);
    writer.string(message.description);

    const accessConfigUpdates = message.accessConfigUpdates;
    for (let i: i32 = 0; i < accessConfigUpdates.length; ++i) {
      writer.uint32(26);
      writer.fork();
      AccessConfigUpdate.encode(accessConfigUpdates[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): UpdateInstantiateConfigProposal {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new UpdateInstantiateConfigProposal();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.title = reader.string();
          break;

        case 2:
          message.description = reader.string();
          break;

        case 3:
          message.accessConfigUpdates.push(
            AccessConfigUpdate.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  title: string;
  description: string;
  accessConfigUpdates: Array<AccessConfigUpdate>;

  constructor(
    title: string = "",
    description: string = "",
    accessConfigUpdates: Array<AccessConfigUpdate> = []
  ) {
    this.title = title;
    this.description = description;
    this.accessConfigUpdates = accessConfigUpdates;
  }
}
