// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { UninterpretedOption } from "./UninterpretedOption";

export class ServiceOptions {
  static encode(message: ServiceOptions, writer: Writer): void {
    writer.uint32(264);
    writer.bool(message.deprecated);

    const uninterpretedOption = message.uninterpretedOption;
    for (let i: i32 = 0; i < uninterpretedOption.length; ++i) {
      writer.uint32(7994);
      writer.fork();
      UninterpretedOption.encode(uninterpretedOption[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ServiceOptions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ServiceOptions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 33:
          message.deprecated = reader.bool();
          break;

        case 999:
          message.uninterpretedOption.push(
            UninterpretedOption.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  deprecated: bool;
  uninterpretedOption: Array<UninterpretedOption>;

  constructor(
    deprecated: bool = false,
    uninterpretedOption: Array<UninterpretedOption> = []
  ) {
    this.deprecated = deprecated;
    this.uninterpretedOption = uninterpretedOption;
  }
}
