// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { RpcCall } from "./RpcCall";

export class RpcCalls {
  static encode(message: RpcCalls, writer: Writer): void {
    const calls = message.calls;
    for (let i: i32 = 0; i < calls.length; ++i) {
      writer.uint32(10);
      writer.fork();
      RpcCall.encode(calls[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): RpcCalls {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RpcCalls();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.calls.push(RpcCall.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  calls: Array<RpcCall>;

  constructor(calls: Array<RpcCall> = []) {
    this.calls = calls;
  }
}
