// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class RpcCall {
  static encode(message: RpcCall, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.toAddr);

    writer.uint32(18);
    writer.bytes(message.data);
  }

  static decode(reader: Reader, length: i32): RpcCall {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RpcCall();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toAddr = reader.bytes();
          break;

        case 2:
          message.data = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toAddr: Uint8Array;
  data: Uint8Array;

  constructor(
    toAddr: Uint8Array = new Uint8Array(0),
    data: Uint8Array = new Uint8Array(0)
  ) {
    this.toAddr = toAddr;
    this.data = data;
  }
}
