# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sf/substreams/options.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'sf/substreams/options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsf/substreams/options.proto\x12\rsf.substreams\x1a google/protobuf/descriptor.proto\"\\\n\x0c\x46ieldOptions\x12$\n\x0eload_from_file\x18\x01 \x01(\x08R\x0cloadFromFile\x12&\n\x0fzip_from_folder\x18\x02 \x01(\x08R\rzipFromFolder:X\n\x07options\x12\x1d.google.protobuf.FieldOptions\x18\x98\x11 \x01(\x0b\x32\x1b.sf.substreams.FieldOptionsR\x07options\x88\x01\x01\x42\xb9\x01\n\x11\x63om.sf.substreamsB\x0cOptionsProtoP\x01ZAgithub.com/streamingfast/substreams/pb/sf/substreams;pbsubstreams\xa2\x02\x03SSX\xaa\x02\rSf.Substreams\xca\x02\rSf\\Substreams\xe2\x02\x19Sf\\Substreams\\GPBMetadata\xea\x02\x0eSf::Substreamsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.substreams.options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.sf.substreamsB\014OptionsProtoP\001ZAgithub.com/streamingfast/substreams/pb/sf/substreams;pbsubstreams\242\002\003SSX\252\002\rSf.Substreams\312\002\rSf\\Substreams\342\002\031Sf\\Substreams\\GPBMetadata\352\002\016Sf::Substreams'
  _globals['_FIELDOPTIONS']._serialized_start=80
  _globals['_FIELDOPTIONS']._serialized_end=172
# @@protoc_insertion_point(module_scope)
