// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { MarketVolume } from "./MarketVolume";

export class AggregateAccountVolumeRecord {
  static encode(message: AggregateAccountVolumeRecord, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.account);

    const marketVolumes = message.marketVolumes;
    for (let i: i32 = 0; i < marketVolumes.length; ++i) {
      writer.uint32(18);
      writer.fork();
      MarketVolume.encode(marketVolumes[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): AggregateAccountVolumeRecord {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AggregateAccountVolumeRecord();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.string();
          break;

        case 2:
          message.marketVolumes.push(
            MarketVolume.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: string;
  marketVolumes: Array<MarketVolume>;

  constructor(account: string = "", marketVolumes: Array<MarketVolume> = []) {
    this.account = account;
    this.marketVolumes = marketVolumes;
  }
}
