// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { OracleType } from "../../oracle/v1beta1/OracleType";
import { MarketStatus } from "./MarketStatus";

export class BinaryOptionsMarket {
  static encode(message: BinaryOptionsMarket, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.ticker);

    writer.uint32(18);
    writer.string(message.oracleSymbol);

    writer.uint32(26);
    writer.string(message.oracleProvider);

    writer.uint32(32);
    writer.int32(message.oracleType);

    writer.uint32(40);
    writer.uint32(message.oracleScaleFactor);

    writer.uint32(48);
    writer.int64(message.expirationTimestamp);

    writer.uint32(56);
    writer.int64(message.settlementTimestamp);

    writer.uint32(66);
    writer.string(message.admin);

    writer.uint32(74);
    writer.string(message.quoteDenom);

    writer.uint32(82);
    writer.string(message.marketId);

    writer.uint32(90);
    writer.string(message.makerFeeRate);

    writer.uint32(98);
    writer.string(message.takerFeeRate);

    writer.uint32(106);
    writer.string(message.relayerFeeShareRate);

    writer.uint32(112);
    writer.int32(message.status);

    writer.uint32(122);
    writer.string(message.minPriceTickSize);

    writer.uint32(130);
    writer.string(message.minQuantityTickSize);

    writer.uint32(138);
    writer.string(message.settlementPrice);
  }

  static decode(reader: Reader, length: i32): BinaryOptionsMarket {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BinaryOptionsMarket();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.ticker = reader.string();
          break;

        case 2:
          message.oracleSymbol = reader.string();
          break;

        case 3:
          message.oracleProvider = reader.string();
          break;

        case 4:
          message.oracleType = reader.int32();
          break;

        case 5:
          message.oracleScaleFactor = reader.uint32();
          break;

        case 6:
          message.expirationTimestamp = reader.int64();
          break;

        case 7:
          message.settlementTimestamp = reader.int64();
          break;

        case 8:
          message.admin = reader.string();
          break;

        case 9:
          message.quoteDenom = reader.string();
          break;

        case 10:
          message.marketId = reader.string();
          break;

        case 11:
          message.makerFeeRate = reader.string();
          break;

        case 12:
          message.takerFeeRate = reader.string();
          break;

        case 13:
          message.relayerFeeShareRate = reader.string();
          break;

        case 14:
          message.status = reader.int32();
          break;

        case 15:
          message.minPriceTickSize = reader.string();
          break;

        case 16:
          message.minQuantityTickSize = reader.string();
          break;

        case 17:
          message.settlementPrice = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  ticker: string;
  oracleSymbol: string;
  oracleProvider: string;
  oracleType: OracleType;
  oracleScaleFactor: u32;
  expirationTimestamp: i64;
  settlementTimestamp: i64;
  admin: string;
  quoteDenom: string;
  marketId: string;
  makerFeeRate: string;
  takerFeeRate: string;
  relayerFeeShareRate: string;
  status: MarketStatus;
  minPriceTickSize: string;
  minQuantityTickSize: string;
  settlementPrice: string;

  constructor(
    ticker: string = "",
    oracleSymbol: string = "",
    oracleProvider: string = "",
    oracleType: OracleType = 0,
    oracleScaleFactor: u32 = 0,
    expirationTimestamp: i64 = 0,
    settlementTimestamp: i64 = 0,
    admin: string = "",
    quoteDenom: string = "",
    marketId: string = "",
    makerFeeRate: string = "",
    takerFeeRate: string = "",
    relayerFeeShareRate: string = "",
    status: MarketStatus = 0,
    minPriceTickSize: string = "",
    minQuantityTickSize: string = "",
    settlementPrice: string = ""
  ) {
    this.ticker = ticker;
    this.oracleSymbol = oracleSymbol;
    this.oracleProvider = oracleProvider;
    this.oracleType = oracleType;
    this.oracleScaleFactor = oracleScaleFactor;
    this.expirationTimestamp = expirationTimestamp;
    this.settlementTimestamp = settlementTimestamp;
    this.admin = admin;
    this.quoteDenom = quoteDenom;
    this.marketId = marketId;
    this.makerFeeRate = makerFeeRate;
    this.takerFeeRate = takerFeeRate;
    this.relayerFeeShareRate = relayerFeeShareRate;
    this.status = status;
    this.minPriceTickSize = minPriceTickSize;
    this.minQuantityTickSize = minQuantityTickSize;
    this.settlementPrice = settlementPrice;
  }
}
