// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class DenomDecimals {
  static encode(message: DenomDecimals, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.denom);

    writer.uint32(16);
    writer.uint64(message.decimals);
  }

  static decode(reader: Reader, length: i32): DenomDecimals {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DenomDecimals();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.denom = reader.string();
          break;

        case 2:
          message.decimals = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  denom: string;
  decimals: u64;

  constructor(denom: string = "", decimals: u64 = 0) {
    this.denom = denom;
    this.decimals = decimals;
  }
}
