// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class Deposit {
  static encode(message: Deposit, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.availableBalance);

    writer.uint32(18);
    writer.string(message.totalBalance);
  }

  static decode(reader: Reader, length: i32): Deposit {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Deposit();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.availableBalance = reader.string();
          break;

        case 2:
          message.totalBalance = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  availableBalance: string;
  totalBalance: string;

  constructor(availableBalance: string = "", totalBalance: string = "") {
    this.availableBalance = availableBalance;
    this.totalBalance = totalBalance;
  }
}
