// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { OrderInfo } from "./OrderInfo";
import { OrderType } from "./OrderType";

export class DerivativeLimitOrder {
  static encode(message: DerivativeLimitOrder, writer: Writer): void {
    const orderInfo = message.orderInfo;
    if (orderInfo !== null) {
      writer.uint32(10);
      writer.fork();
      OrderInfo.encode(orderInfo, writer);
      writer.ldelim();
    }

    writer.uint32(16);
    writer.int32(message.orderType);

    writer.uint32(26);
    writer.string(message.margin);

    writer.uint32(34);
    writer.string(message.fillable);

    writer.uint32(42);
    writer.string(message.triggerPrice);

    writer.uint32(50);
    writer.bytes(message.orderHash);
  }

  static decode(reader: Reader, length: i32): DerivativeLimitOrder {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DerivativeLimitOrder();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.orderInfo = OrderInfo.decode(reader, reader.uint32());
          break;

        case 2:
          message.orderType = reader.int32();
          break;

        case 3:
          message.margin = reader.string();
          break;

        case 4:
          message.fillable = reader.string();
          break;

        case 5:
          message.triggerPrice = reader.string();
          break;

        case 6:
          message.orderHash = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  orderInfo: OrderInfo | null;
  orderType: OrderType;
  margin: string;
  fillable: string;
  triggerPrice: string;
  orderHash: Uint8Array;

  constructor(
    orderInfo: OrderInfo | null = null,
    orderType: OrderType = 0,
    margin: string = "",
    fillable: string = "",
    triggerPrice: string = "",
    orderHash: Uint8Array = new Uint8Array(0)
  ) {
    this.orderInfo = orderInfo;
    this.orderType = orderType;
    this.margin = margin;
    this.fillable = fillable;
    this.triggerPrice = triggerPrice;
    this.orderHash = orderHash;
  }
}
