// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { VolumeRecord } from "./VolumeRecord";

export class MarketVolume {
  static encode(message: MarketVolume, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.marketId);

    const volume = message.volume;
    if (volume !== null) {
      writer.uint32(18);
      writer.fork();
      VolumeRecord.encode(volume, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MarketVolume {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MarketVolume();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.marketId = reader.string();
          break;

        case 2:
          message.volume = VolumeRecord.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  marketId: string;
  volume: VolumeRecord | null;

  constructor(marketId: string = "", volume: VolumeRecord | null = null) {
    this.marketId = marketId;
    this.volume = volume;
  }
}
