// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgBatchCancelBinaryOptionsOrdersResponse {
  static encode(
    message: MsgBatchCancelBinaryOptionsOrdersResponse,
    writer: Writer
  ): void {
    const success = message.success;
    if (success.length !== 0) {
      for (let i: i32 = 0; i < success.length; ++i) {
        writer.uint32(8);
        writer.bool(success[i]);
      }
    }
  }

  static decode(
    reader: Reader,
    length: i32
  ): MsgBatchCancelBinaryOptionsOrdersResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgBatchCancelBinaryOptionsOrdersResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.success.push(reader.bool());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  success: Array<bool>;

  constructor(success: Array<bool> = []) {
    this.success = success;
  }
}
