// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgBatchCreateDerivativeLimitOrdersResponse {
  static encode(
    message: MsgBatchCreateDerivativeLimitOrdersResponse,
    writer: Writer
  ): void {
    const orderHashes = message.orderHashes;
    if (orderHashes.length !== 0) {
      for (let i: i32 = 0; i < orderHashes.length; ++i) {
        writer.uint32(10);
        writer.string(orderHashes[i]);
      }
    }
  }

  static decode(
    reader: Reader,
    length: i32
  ): MsgBatchCreateDerivativeLimitOrdersResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgBatchCreateDerivativeLimitOrdersResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.orderHashes.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  orderHashes: Array<string>;

  constructor(orderHashes: Array<string> = []) {
    this.orderHashes = orderHashes;
  }
}
