// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgIncreasePositionMargin {
  static encode(message: MsgIncreasePositionMargin, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    writer.uint32(18);
    writer.string(message.sourceSubaccountId);

    writer.uint32(26);
    writer.string(message.destinationSubaccountId);

    writer.uint32(34);
    writer.string(message.marketId);

    writer.uint32(42);
    writer.string(message.amount);
  }

  static decode(reader: Reader, length: i32): MsgIncreasePositionMargin {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgIncreasePositionMargin();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.sourceSubaccountId = reader.string();
          break;

        case 3:
          message.destinationSubaccountId = reader.string();
          break;

        case 4:
          message.marketId = reader.string();
          break;

        case 5:
          message.amount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  sourceSubaccountId: string;
  destinationSubaccountId: string;
  marketId: string;
  amount: string;

  constructor(
    sender: string = "",
    sourceSubaccountId: string = "",
    destinationSubaccountId: string = "",
    marketId: string = "",
    amount: string = ""
  ) {
    this.sender = sender;
    this.sourceSubaccountId = sourceSubaccountId;
    this.destinationSubaccountId = destinationSubaccountId;
    this.marketId = marketId;
    this.amount = amount;
  }
}
