// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgRewardsOptOut {
  static encode(message: MsgRewardsOptOut, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);
  }

  static decode(reader: Reader, length: i32): MsgRewardsOptOut {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgRewardsOptOut();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;

  constructor(sender: string = "") {
    this.sender = sender;
  }
}
