// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { MsgSignData } from "./MsgSignData";

export class MsgSignDoc {
  static encode(message: MsgSignDoc, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.signType);

    const value = message.value;
    if (value !== null) {
      writer.uint32(18);
      writer.fork();
      MsgSignData.encode(value, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgSignDoc {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgSignDoc();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signType = reader.string();
          break;

        case 2:
          message.value = MsgSignData.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signType: string;
  value: MsgSignData | null;

  constructor(signType: string = "", value: MsgSignData | null = null) {
    this.signType = signType;
    this.value = value;
  }
}
