// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Coin } from "../../../cosmos/base/v1beta1/Coin";

export class MsgSubaccountTransfer {
  static encode(message: MsgSubaccountTransfer, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    writer.uint32(18);
    writer.string(message.sourceSubaccountId);

    writer.uint32(26);
    writer.string(message.destinationSubaccountId);

    const amount = message.amount;
    if (amount !== null) {
      writer.uint32(34);
      writer.fork();
      Coin.encode(amount, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgSubaccountTransfer {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgSubaccountTransfer();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.sourceSubaccountId = reader.string();
          break;

        case 3:
          message.destinationSubaccountId = reader.string();
          break;

        case 4:
          message.amount = Coin.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  sourceSubaccountId: string;
  destinationSubaccountId: string;
  amount: Coin | null;

  constructor(
    sender: string = "",
    sourceSubaccountId: string = "",
    destinationSubaccountId: string = "",
    amount: Coin | null = null
  ) {
    this.sender = sender;
    this.sourceSubaccountId = sourceSubaccountId;
    this.destinationSubaccountId = destinationSubaccountId;
    this.amount = amount;
  }
}
