// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class OrderInfo {
  static encode(message: OrderInfo, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.subaccountId);

    writer.uint32(18);
    writer.string(message.feeRecipient);

    writer.uint32(26);
    writer.string(message.price);

    writer.uint32(34);
    writer.string(message.quantity);

    writer.uint32(42);
    writer.string(message.cid);
  }

  static decode(reader: Reader, length: i32): OrderInfo {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new OrderInfo();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.subaccountId = reader.string();
          break;

        case 2:
          message.feeRecipient = reader.string();
          break;

        case 3:
          message.price = reader.string();
          break;

        case 4:
          message.quantity = reader.string();
          break;

        case 5:
          message.cid = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  subaccountId: string;
  feeRecipient: string;
  price: string;
  quantity: string;
  cid: string;

  constructor(
    subaccountId: string = "",
    feeRecipient: string = "",
    price: string = "",
    quantity: string = "",
    cid: string = ""
  ) {
    this.subaccountId = subaccountId;
    this.feeRecipient = feeRecipient;
    this.price = price;
    this.quantity = quantity;
    this.cid = cid;
  }
}
