// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class PerpetualMarketFunding {
  static encode(message: PerpetualMarketFunding, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.cumulativeFunding);

    writer.uint32(18);
    writer.string(message.cumulativePrice);

    writer.uint32(24);
    writer.int64(message.lastTimestamp);
  }

  static decode(reader: Reader, length: i32): PerpetualMarketFunding {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PerpetualMarketFunding();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.cumulativeFunding = reader.string();
          break;

        case 2:
          message.cumulativePrice = reader.string();
          break;

        case 3:
          message.lastTimestamp = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  cumulativeFunding: string;
  cumulativePrice: string;
  lastTimestamp: i64;

  constructor(
    cumulativeFunding: string = "",
    cumulativePrice: string = "",
    lastTimestamp: i64 = 0
  ) {
    this.cumulativeFunding = cumulativeFunding;
    this.cumulativePrice = cumulativePrice;
    this.lastTimestamp = lastTimestamp;
  }
}
