// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class PointsMultiplier {
  static encode(message: PointsMultiplier, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.makerPointsMultiplier);

    writer.uint32(18);
    writer.string(message.takerPointsMultiplier);
  }

  static decode(reader: Reader, length: i32): PointsMultiplier {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PointsMultiplier();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.makerPointsMultiplier = reader.string();
          break;

        case 2:
          message.takerPointsMultiplier = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  makerPointsMultiplier: string;
  takerPointsMultiplier: string;

  constructor(
    makerPointsMultiplier: string = "",
    takerPointsMultiplier: string = ""
  ) {
    this.makerPointsMultiplier = makerPointsMultiplier;
    this.takerPointsMultiplier = takerPointsMultiplier;
  }
}
