// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class Position {
  static encode(message: Position, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.isLong);

    writer.uint32(18);
    writer.string(message.quantity);

    writer.uint32(26);
    writer.string(message.entryPrice);

    writer.uint32(34);
    writer.string(message.margin);

    writer.uint32(42);
    writer.string(message.cumulativeFundingEntry);
  }

  static decode(reader: Reader, length: i32): Position {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Position();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.isLong = reader.bool();
          break;

        case 2:
          message.quantity = reader.string();
          break;

        case 3:
          message.entryPrice = reader.string();
          break;

        case 4:
          message.margin = reader.string();
          break;

        case 5:
          message.cumulativeFundingEntry = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  isLong: bool;
  quantity: string;
  entryPrice: string;
  margin: string;
  cumulativeFundingEntry: string;

  constructor(
    isLong: bool = false,
    quantity: string = "",
    entryPrice: string = "",
    margin: string = "",
    cumulativeFundingEntry: string = ""
  ) {
    this.isLong = isLong;
    this.quantity = quantity;
    this.entryPrice = entryPrice;
    this.margin = margin;
    this.cumulativeFundingEntry = cumulativeFundingEntry;
  }
}
