// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class SpotMarketOrderResults {
  static encode(message: SpotMarketOrderResults, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.quantity);

    writer.uint32(18);
    writer.string(message.price);

    writer.uint32(26);
    writer.string(message.fee);
  }

  static decode(reader: Reader, length: i32): SpotMarketOrderResults {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SpotMarketOrderResults();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.quantity = reader.string();
          break;

        case 2:
          message.price = reader.string();
          break;

        case 3:
          message.fee = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  quantity: string;
  price: string;
  fee: string;

  constructor(quantity: string = "", price: string = "", fee: string = "") {
    this.quantity = quantity;
    this.price = price;
    this.fee = fee;
  }
}
