// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class SubaccountOrder {
  static encode(message: SubaccountOrder, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.price);

    writer.uint32(18);
    writer.string(message.quantity);

    writer.uint32(24);
    writer.bool(message.isReduceOnly);
  }

  static decode(reader: Reader, length: i32): SubaccountOrder {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SubaccountOrder();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.price = reader.string();
          break;

        case 2:
          message.quantity = reader.string();
          break;

        case 3:
          message.isReduceOnly = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  price: string;
  quantity: string;
  isReduceOnly: bool;

  constructor(
    price: string = "",
    quantity: string = "",
    isReduceOnly: bool = false
  ) {
    this.price = price;
    this.quantity = quantity;
    this.isReduceOnly = isReduceOnly;
  }
}
