// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class SubaccountTradeNonce {
  static encode(message: SubaccountTradeNonce, writer: Writer): void {
    writer.uint32(8);
    writer.uint32(message.nonce);
  }

  static decode(reader: Reader, length: i32): SubaccountTradeNonce {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SubaccountTradeNonce();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.nonce = reader.uint32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  nonce: u32;

  constructor(nonce: u32 = 0) {
    this.nonce = nonce;
  }
}
