// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class TradeLog {
  static encode(message: TradeLog, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.quantity);

    writer.uint32(18);
    writer.string(message.price);

    writer.uint32(26);
    writer.bytes(message.subaccountId);

    writer.uint32(34);
    writer.string(message.fee);

    writer.uint32(42);
    writer.bytes(message.orderHash);

    writer.uint32(50);
    writer.bytes(message.feeRecipientAddress);

    writer.uint32(58);
    writer.string(message.cid);
  }

  static decode(reader: Reader, length: i32): TradeLog {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TradeLog();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.quantity = reader.string();
          break;

        case 2:
          message.price = reader.string();
          break;

        case 3:
          message.subaccountId = reader.bytes();
          break;

        case 4:
          message.fee = reader.string();
          break;

        case 5:
          message.orderHash = reader.bytes();
          break;

        case 6:
          message.feeRecipientAddress = reader.bytes();
          break;

        case 7:
          message.cid = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  quantity: string;
  price: string;
  subaccountId: Uint8Array;
  fee: string;
  orderHash: Uint8Array;
  feeRecipientAddress: Uint8Array;
  cid: string;

  constructor(
    quantity: string = "",
    price: string = "",
    subaccountId: Uint8Array = new Uint8Array(0),
    fee: string = "",
    orderHash: Uint8Array = new Uint8Array(0),
    feeRecipientAddress: Uint8Array = new Uint8Array(0),
    cid: string = ""
  ) {
    this.quantity = quantity;
    this.price = price;
    this.subaccountId = subaccountId;
    this.fee = fee;
    this.orderHash = orderHash;
    this.feeRecipientAddress = feeRecipientAddress;
    this.cid = cid;
  }
}
