// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class ERC20ToDenom {
  static encode(message: ERC20ToDenom, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.erc20);

    writer.uint32(18);
    writer.string(message.denom);
  }

  static decode(reader: Reader, length: i32): ERC20ToDenom {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ERC20ToDenom();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.erc20 = reader.string();
          break;

        case 2:
          message.denom = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  erc20: string;
  denom: string;

  constructor(erc20: string = "", denom: string = "") {
    this.erc20 = erc20;
    this.denom = denom;
  }
}
