// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgCancelSendToEth {
  static encode(message: MsgCancelSendToEth, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.transactionId);

    writer.uint32(18);
    writer.string(message.sender);
  }

  static decode(reader: Reader, length: i32): MsgCancelSendToEth {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgCancelSendToEth();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.transactionId = reader.uint64();
          break;

        case 2:
          message.sender = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  transactionId: u64;
  sender: string;

  constructor(transactionId: u64 = 0, sender: string = "") {
    this.transactionId = transactionId;
    this.sender = sender;
  }
}
