// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgWithdrawClaim {
  static encode(message: MsgWithdrawClaim, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.eventNonce);

    writer.uint32(16);
    writer.uint64(message.blockHeight);

    writer.uint32(24);
    writer.uint64(message.batchNonce);

    writer.uint32(34);
    writer.string(message.tokenContract);

    writer.uint32(42);
    writer.string(message.orchestrator);
  }

  static decode(reader: Reader, length: i32): MsgWithdrawClaim {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgWithdrawClaim();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.eventNonce = reader.uint64();
          break;

        case 2:
          message.blockHeight = reader.uint64();
          break;

        case 3:
          message.batchNonce = reader.uint64();
          break;

        case 4:
          message.tokenContract = reader.string();
          break;

        case 5:
          message.orchestrator = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  eventNonce: u64;
  blockHeight: u64;
  batchNonce: u64;
  tokenContract: string;
  orchestrator: string;

  constructor(
    eventNonce: u64 = 0,
    blockHeight: u64 = 0,
    batchNonce: u64 = 0,
    tokenContract: string = "",
    orchestrator: string = ""
  ) {
    this.eventNonce = eventNonce;
    this.blockHeight = blockHeight;
    this.batchNonce = batchNonce;
    this.tokenContract = tokenContract;
    this.orchestrator = orchestrator;
  }
}
