// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class BlockRange {
  static encode(message: BlockRange, writer: Writer): void {
    writer.uint32(16);
    writer.uint64(message.startBlock);

    writer.uint32(24);
    writer.uint64(message.endBlock);
  }

  static decode(reader: Reader, length: i32): BlockRange {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BlockRange();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          message.startBlock = reader.uint64();
          break;

        case 3:
          message.endBlock = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  startBlock: u64;
  endBlock: u64;

  constructor(startBlock: u64 = 0, endBlock: u64 = 0) {
    this.startBlock = startBlock;
    this.endBlock = endBlock;
  }
}
