// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class ExternalCallMetric {
  static encode(message: ExternalCallMetric, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    writer.uint32(16);
    writer.uint64(message.count);

    writer.uint32(24);
    writer.uint64(message.timeMs);
  }

  static decode(reader: Reader, length: i32): ExternalCallMetric {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ExternalCallMetric();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.count = reader.uint64();
          break;

        case 3:
          message.timeMs = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  count: u64;
  timeMs: u64;

  constructor(name: string = "", count: u64 = 0, timeMs: u64 = 0) {
    this.name = name;
    this.count = count;
    this.timeMs = timeMs;
  }
}
