// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class ProcessedBytes {
  static encode(message: ProcessedBytes, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.totalBytesRead);

    writer.uint32(16);
    writer.uint64(message.totalBytesWritten);
  }

  static decode(reader: Reader, length: i32): ProcessedBytes {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProcessedBytes();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.totalBytesRead = reader.uint64();
          break;

        case 2:
          message.totalBytesWritten = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  totalBytesRead: u64;
  totalBytesWritten: u64;

  constructor(totalBytesRead: u64 = 0, totalBytesWritten: u64 = 0) {
    this.totalBytesRead = totalBytesRead;
    this.totalBytesWritten = totalBytesWritten;
  }
}
