// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Operation } from "./StoreDelta/Operation";

export class StoreDelta {
  static encode(message: StoreDelta, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.operation);

    writer.uint32(16);
    writer.uint64(message.ordinal);

    writer.uint32(26);
    writer.string(message.key);

    writer.uint32(34);
    writer.bytes(message.oldValue);

    writer.uint32(42);
    writer.bytes(message.newValue);
  }

  static decode(reader: Reader, length: i32): StoreDelta {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StoreDelta();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.operation = reader.int32();
          break;

        case 2:
          message.ordinal = reader.uint64();
          break;

        case 3:
          message.key = reader.string();
          break;

        case 4:
          message.oldValue = reader.bytes();
          break;

        case 5:
          message.newValue = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  operation: Operation;
  ordinal: u64;
  key: string;
  oldValue: Uint8Array;
  newValue: Uint8Array;

  constructor(
    operation: Operation = 0,
    ordinal: u64 = 0,
    key: string = "",
    oldValue: Uint8Array = new Uint8Array(0),
    newValue: Uint8Array = new Uint8Array(0)
  ) {
    this.operation = operation;
    this.ordinal = ordinal;
    this.key = key;
    this.oldValue = oldValue;
    this.newValue = newValue;
  }
}
