// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { PriceState } from "./PriceState";

export class ChainlinkPriceState {
  static encode(message: ChainlinkPriceState, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.feedId);

    writer.uint32(18);
    writer.string(message.answer);

    writer.uint32(24);
    writer.uint64(message.timestamp);

    const priceState = message.priceState;
    if (priceState !== null) {
      writer.uint32(34);
      writer.fork();
      PriceState.encode(priceState, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ChainlinkPriceState {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChainlinkPriceState();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.feedId = reader.string();
          break;

        case 2:
          message.answer = reader.string();
          break;

        case 3:
          message.timestamp = reader.uint64();
          break;

        case 4:
          message.priceState = PriceState.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  feedId: string;
  answer: string;
  timestamp: u64;
  priceState: PriceState | null;

  constructor(
    feedId: string = "",
    answer: string = "",
    timestamp: u64 = 0,
    priceState: PriceState | null = null
  ) {
    this.feedId = feedId;
    this.answer = answer;
    this.timestamp = timestamp;
    this.priceState = priceState;
  }
}
