// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { PriceState } from "./PriceState";

export class CoinbasePriceState {
  static encode(message: CoinbasePriceState, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.kind);

    writer.uint32(16);
    writer.uint64(message.timestamp);

    writer.uint32(26);
    writer.string(message.key);

    writer.uint32(32);
    writer.uint64(message.value);

    const priceState = message.priceState;
    if (priceState !== null) {
      writer.uint32(42);
      writer.fork();
      PriceState.encode(priceState, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CoinbasePriceState {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CoinbasePriceState();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.kind = reader.string();
          break;

        case 2:
          message.timestamp = reader.uint64();
          break;

        case 3:
          message.key = reader.string();
          break;

        case 4:
          message.value = reader.uint64();
          break;

        case 5:
          message.priceState = PriceState.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  kind: string;
  timestamp: u64;
  key: string;
  value: u64;
  priceState: PriceState | null;

  constructor(
    kind: string = "",
    timestamp: u64 = 0,
    key: string = "",
    value: u64 = 0,
    priceState: PriceState | null = null
  ) {
    this.kind = kind;
    this.timestamp = timestamp;
    this.key = key;
    this.value = value;
    this.priceState = priceState;
  }
}
