// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class PriceFeedInfo {
  static encode(message: PriceFeedInfo, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.base);

    writer.uint32(18);
    writer.string(message.quote);
  }

  static decode(reader: Reader, length: i32): PriceFeedInfo {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PriceFeedInfo();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.base = reader.string();
          break;

        case 2:
          message.quote = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  base: string;
  quote: string;

  constructor(base: string = "", quote: string = "") {
    this.base = base;
    this.quote = quote;
  }
}
