# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sf.substreams.sink.service.v1 import service_pb2 as sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2


class ProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Deploy = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/Deploy',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.DeployRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/Update',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.UpdateRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/Info',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.InfoRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/List',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ListRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/Pause',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.PauseRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.PauseResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/Stop',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.StopRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.StopResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/Resume',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ResumeRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/sf.substreams.sink.service.v1.Provider/Remove',
                request_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.RemoveRequest.SerializeToString,
                response_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.RemoveResponse.FromString,
                _registered_method=True)


class ProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Deploy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Deploy': grpc.unary_unary_rpc_method_handler(
                    servicer.Deploy,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.DeployRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.DeployResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.UpdateRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.UpdateResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.InfoRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.InfoResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ListRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ListResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.PauseRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.PauseResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.StopRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.StopResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ResumeRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ResumeResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.RemoveRequest.FromString,
                    response_serializer=sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.RemoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sf.substreams.sink.service.v1.Provider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sf.substreams.sink.service.v1.Provider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Provider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Deploy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/Deploy',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.DeployRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/Update',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.UpdateRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/Info',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.InfoRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/List',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ListRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/Pause',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.PauseRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.PauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/Stop',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.StopRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/Resume',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ResumeRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.substreams.sink.service.v1.Provider/Remove',
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.RemoveRequest.SerializeToString,
            sf_dot_substreams_dot_sink_dot_service_dot_v1_dot_service__pb2.RemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
