// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class KindMap {
  static encode(message: KindMap, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.outputType);
  }

  static decode(reader: Reader, length: i32): KindMap {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new KindMap();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.outputType = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  outputType: string;

  constructor(outputType: string = "") {
    this.outputType = outputType;
  }
}
