export const TOKEN: string = "eyJhbGciOiJLTVNFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIwMjcxMDUzOTQsImp0aSI6ImE2ZGM0YzRkLTc4NGQtNGYzYi05ZGEzLWJiOTg4MzY0Y2EyZiIsImlhdCI6MTcxMTc0NTM5NCwiaXNzIjoiZGZ1c2UuaW8iLCJzdWIiOiIwYmV2dWFiZWY1NGJlY2Q3NzQxYmYiLCJ2IjoxLCJha2kiOiIwNDUxNjllNTY5ZTFjMDgwY2IzOTg0YjU4ZTExMDE0ZWZhZTU3MGUxMGE1ZTE1NzEzNzhjZGNkYTU3ZTAzZmY2IiwidWlkIjoiMGJldnVhYmVmNTRiZWNkNzc0MWJmIiwiY2ZnIjp7IlNVQlNUUkVBTVNfUEFSQUxMRUxfSk9CUyI6Ijc1In19.wAtPS8S6d6eukMkt_7SdZ7eP6fbAhM8-0ks-RaKDoIkfbooOxnlcesM1Q8fqSNZlqtpUqsmwk_cai4gbJelXJQ"
export const ENDPOINT = "https://mainnet.eth.streamingfast.io"
export const SPKG = "https://spkg.io/streamingfast/ethereum-explorer-v0.1.2.spkg"
export const MODULE = "map_block_meta"
export const START_BLOCK = 100000
export const STOP_BLOCK = '+100'