// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

export enum UpdatePolicy {
  UPDATE_POLICY_UNSET = 0,
  UPDATE_POLICY_SET = 1,
  UPDATE_POLICY_SET_IF_NOT_EXISTS = 2,
  UPDATE_POLICY_ADD = 3,
  UPDATE_POLICY_MIN = 4,
  UPDATE_POLICY_MAX = 5,
  UPDATE_POLICY_APPEND = 6,
}
