// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class Binary {
  static encode(message: Binary, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.type);

    writer.uint32(18);
    writer.bytes(message.content);
  }

  static decode(reader: Reader, length: i32): Binary {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Binary();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.type = reader.string();
          break;

        case 2:
          message.content = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  type: string;
  content: Uint8Array;

  constructor(type: string = "", content: Uint8Array = new Uint8Array(0)) {
    this.type = type;
    this.content = content;
  }
}
