// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { DecCoin } from "../../base/v1beta1/DecCoin";

export class DelegationDelegatorReward {
  static encode(message: DelegationDelegatorReward, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.validatorAddress);

    const reward = message.reward;
    for (let i: i32 = 0; i < reward.length; ++i) {
      writer.uint32(18);
      writer.fork();
      DecCoin.encode(reward[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DelegationDelegatorReward {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DelegationDelegatorReward();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.validatorAddress = reader.string();
          break;

        case 2:
          message.reward.push(DecCoin.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  validatorAddress: string;
  reward: Array<DecCoin>;

  constructor(validatorAddress: string = "", reward: Array<DecCoin> = []) {
    this.validatorAddress = validatorAddress;
    this.reward = reward;
  }
}
