// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { ValidatorSlashEvent } from "./ValidatorSlashEvent";

export class ValidatorSlashEvents {
  static encode(message: ValidatorSlashEvents, writer: Writer): void {
    const validatorSlashEvents = message.validatorSlashEvents;
    for (let i: i32 = 0; i < validatorSlashEvents.length; ++i) {
      writer.uint32(10);
      writer.fork();
      ValidatorSlashEvent.encode(validatorSlashEvents[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ValidatorSlashEvents {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ValidatorSlashEvents();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.validatorSlashEvents.push(
            ValidatorSlashEvent.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  validatorSlashEvents: Array<ValidatorSlashEvent>;

  constructor(validatorSlashEvents: Array<ValidatorSlashEvent> = []) {
    this.validatorSlashEvents = validatorSlashEvents;
  }
}
