// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { DecCoin } from "../../base/v1beta1/DecCoin";

export class ValidatorAccumulatedCommission {
  static encode(message: ValidatorAccumulatedCommission, writer: Writer): void {
    const commission = message.commission;
    for (let i: i32 = 0; i < commission.length; ++i) {
      writer.uint32(10);
      writer.fork();
      DecCoin.encode(commission[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ValidatorAccumulatedCommission {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ValidatorAccumulatedCommission();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.commission.push(DecCoin.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  commission: Array<DecCoin>;

  constructor(commission: Array<DecCoin> = []) {
    this.commission = commission;
  }
}
