// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class ValidatorSlashEvent {
  static encode(message: ValidatorSlashEvent, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.validatorPeriod);

    writer.uint32(18);
    writer.string(message.fraction);
  }

  static decode(reader: Reader, length: i32): ValidatorSlashEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ValidatorSlashEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.validatorPeriod = reader.uint64();
          break;

        case 2:
          message.fraction = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  validatorPeriod: u64;
  fraction: string;

  constructor(validatorPeriod: u64 = 0, fraction: string = "") {
    this.validatorPeriod = validatorPeriod;
    this.fraction = fraction;
  }
}
