// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MultiSignature {
  static encode(message: MultiSignature, writer: Writer): void {
    const signatures = message.signatures;
    if (signatures.length !== 0) {
      for (let i: i32 = 0; i < signatures.length; ++i) {
        writer.uint32(10);
        writer.bytes(signatures[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): MultiSignature {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MultiSignature();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signatures.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signatures: Array<Uint8Array>;

  constructor(signatures: Array<Uint8Array> = []) {
    this.signatures = signatures;
  }
}
