// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class AccountCreation {
  static encode(message: AccountCreation, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.account);

    writer.uint32(16);
    writer.uint64(message.ordinal);
  }

  static decode(reader: Reader, length: i32): AccountCreation {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AccountCreation();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.bytes();
          break;

        case 2:
          message.ordinal = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: Uint8Array;
  ordinal: u64;

  constructor(account: Uint8Array = new Uint8Array(0), ordinal: u64 = 0) {
    this.account = account;
    this.ordinal = ordinal;
  }
}
