// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class BlockRef {
  static encode(message: BlockRef, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.hash);

    writer.uint32(16);
    writer.uint64(message.number);
  }

  static decode(reader: Reader, length: i32): BlockRef {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BlockRef();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.hash = reader.bytes();
          break;

        case 2:
          message.number = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  hash: Uint8Array;
  number: u64;

  constructor(hash: Uint8Array = new Uint8Array(0), number: u64 = 0) {
    this.hash = hash;
    this.number = number;
  }
}
