// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class NonceChange {
  static encode(message: NonceChange, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.address);

    writer.uint32(16);
    writer.uint64(message.oldValue);

    writer.uint32(24);
    writer.uint64(message.newValue);

    writer.uint32(32);
    writer.uint64(message.ordinal);
  }

  static decode(reader: Reader, length: i32): NonceChange {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NonceChange();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.address = reader.bytes();
          break;

        case 2:
          message.oldValue = reader.uint64();
          break;

        case 3:
          message.newValue = reader.uint64();
          break;

        case 4:
          message.ordinal = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  address: Uint8Array;
  oldValue: u64;
  newValue: u64;
  ordinal: u64;

  constructor(
    address: Uint8Array = new Uint8Array(0),
    oldValue: u64 = 0,
    newValue: u64 = 0,
    ordinal: u64 = 0
  ) {
    this.address = address;
    this.oldValue = oldValue;
    this.newValue = newValue;
    this.ordinal = ordinal;
  }
}
