// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class StorageChange {
  static encode(message: StorageChange, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.address);

    writer.uint32(18);
    writer.bytes(message.key);

    writer.uint32(26);
    writer.bytes(message.oldValue);

    writer.uint32(34);
    writer.bytes(message.newValue);

    writer.uint32(40);
    writer.uint64(message.ordinal);
  }

  static decode(reader: Reader, length: i32): StorageChange {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StorageChange();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.address = reader.bytes();
          break;

        case 2:
          message.key = reader.bytes();
          break;

        case 3:
          message.oldValue = reader.bytes();
          break;

        case 4:
          message.newValue = reader.bytes();
          break;

        case 5:
          message.ordinal = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  address: Uint8Array;
  key: Uint8Array;
  oldValue: Uint8Array;
  newValue: Uint8Array;
  ordinal: u64;

  constructor(
    address: Uint8Array = new Uint8Array(0),
    key: Uint8Array = new Uint8Array(0),
    oldValue: Uint8Array = new Uint8Array(0),
    newValue: Uint8Array = new Uint8Array(0),
    ordinal: u64 = 0
  ) {
    this.address = address;
    this.key = key;
    this.oldValue = oldValue;
    this.newValue = newValue;
    this.ordinal = ordinal;
  }
}
