// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Uint64Array } from "./Uint64Array";

export class Uint64NestedArray {
  static encode(message: Uint64NestedArray, writer: Writer): void {
    const val = message.val;
    for (let i: i32 = 0; i < val.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Uint64Array.encode(val[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Uint64NestedArray {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Uint64NestedArray();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.val.push(Uint64Array.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  val: Array<Uint64Array>;

  constructor(val: Array<Uint64Array> = []) {
    this.val = val;
  }
}
