// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class Bid {
  static encode(message: Bid, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.bidder);

    writer.uint32(18);
    writer.string(message.amount);
  }

  static decode(reader: Reader, length: i32): Bid {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Bid();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.bidder = reader.string();
          break;

        case 2:
          message.amount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  bidder: string;
  amount: string;

  constructor(bidder: string = "", amount: string = "") {
    this.bidder = bidder;
    this.amount = amount;
  }
}
