// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class EventBid {
  static encode(message: EventBid, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.bidder);

    writer.uint32(18);
    writer.string(message.amount);

    writer.uint32(24);
    writer.uint64(message.round);
  }

  static decode(reader: Reader, length: i32): EventBid {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EventBid();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.bidder = reader.string();
          break;

        case 2:
          message.amount = reader.string();
          break;

        case 3:
          message.round = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  bidder: string;
  amount: string;
  round: u64;

  constructor(bidder: string = "", amount: string = "", round: u64 = 0) {
    this.bidder = bidder;
    this.amount = amount;
    this.round = round;
  }
}
