// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class Source {
  static encode(message: Source, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.type);
  }

  static decode(reader: Reader, length: i32): Source {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Source();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.type = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  type: string;

  constructor(type: string = "") {
    this.type = type;
  }
}
