// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class InfoRequest {
  static encode(message: InfoRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.deploymentId);
  }

  static decode(reader: Reader, length: i32): InfoRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InfoRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.deploymentId = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  deploymentId: string;

  constructor(deploymentId: string = "") {
    this.deploymentId = deploymentId;
  }
}
