// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { DeploymentWithStatus } from "./DeploymentWithStatus";

export class ListResponse {
  static encode(message: ListResponse, writer: Writer): void {
    const deployments = message.deployments;
    for (let i: i32 = 0; i < deployments.length; ++i) {
      writer.uint32(10);
      writer.fork();
      DeploymentWithStatus.encode(deployments[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ListResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ListResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.deployments.push(
            DeploymentWithStatus.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  deployments: Array<DeploymentWithStatus>;

  constructor(deployments: Array<DeploymentWithStatus> = []) {
    this.deployments = deployments;
  }
}
