// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { DeploymentStatus } from "./DeploymentStatus";

export class ResumeResponse {
  static encode(message: ResumeResponse, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.previousStatus);

    writer.uint32(16);
    writer.int32(message.newStatus);
  }

  static decode(reader: Reader, length: i32): ResumeResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ResumeResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.previousStatus = reader.int32();
          break;

        case 2:
          message.newStatus = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  previousStatus: DeploymentStatus;
  newStatus: DeploymentStatus;

  constructor(
    previousStatus: DeploymentStatus = 0,
    newStatus: DeploymentStatus = 0
  ) {
    this.previousStatus = previousStatus;
    this.newStatus = newStatus;
  }
}
