// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { EventAttributeBytes } from "./EventAttributeBytes";

export class EventBytes {
  static encode(message: EventBytes, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.type);

    const attributes = message.attributes;
    for (let i: i32 = 0; i < attributes.length; ++i) {
      writer.uint32(18);
      writer.fork();
      EventAttributeBytes.encode(attributes[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): EventBytes {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EventBytes();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.type = reader.string();
          break;

        case 2:
          message.attributes.push(
            EventAttributeBytes.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  type: string;
  attributes: Array<EventAttributeBytes>;

  constructor(type: string = "", attributes: Array<EventAttributeBytes> = []) {
    this.type = type;
    this.attributes = attributes;
  }
}
