// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class VersionParams {
  static encode(message: VersionParams, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.app);
  }

  static decode(reader: Reader, length: i32): VersionParams {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VersionParams();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.app = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  app: u64;

  constructor(app: u64 = 0) {
    this.app = app;
  }
}
