# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sf/substreams/v1/deltas.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'sf/substreams/v1/deltas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsf/substreams/v1/deltas.proto\x12\x10sf.substreams.v1\"N\n\x0bStoreDeltas\x12?\n\x0cstore_deltas\x18\x01 \x03(\x0b\x32\x1c.sf.substreams.v1.StoreDeltaR\x0bstoreDeltas\"\xf4\x01\n\nStoreDelta\x12\x44\n\toperation\x18\x01 \x01(\x0e\x32&.sf.substreams.v1.StoreDelta.OperationR\toperation\x12\x18\n\x07ordinal\x18\x02 \x01(\x04R\x07ordinal\x12\x10\n\x03key\x18\x03 \x01(\tR\x03key\x12\x1b\n\told_value\x18\x04 \x01(\x0cR\x08oldValue\x12\x1b\n\tnew_value\x18\x05 \x01(\x0cR\x08newValue\":\n\tOperation\x12\t\n\x05UNSET\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x42\xcb\x01\n\x14\x63om.sf.substreams.v1B\x0b\x44\x65ltasProtoP\x01ZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreams\xa2\x02\x03SSX\xaa\x02\x10Sf.Substreams.V1\xca\x02\x10Sf\\Substreams\\V1\xe2\x02\x1cSf\\Substreams\\V1\\GPBMetadata\xea\x02\x12Sf::Substreams::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.substreams.v1.deltas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.sf.substreams.v1B\013DeltasProtoP\001ZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreams\242\002\003SSX\252\002\020Sf.Substreams.V1\312\002\020Sf\\Substreams\\V1\342\002\034Sf\\Substreams\\V1\\GPBMetadata\352\002\022Sf::Substreams::V1'
  _globals['_STOREDELTAS']._serialized_start=51
  _globals['_STOREDELTAS']._serialized_end=129
  _globals['_STOREDELTA']._serialized_start=132
  _globals['_STOREDELTA']._serialized_end=376
  _globals['_STOREDELTA_OPERATION']._serialized_start=318
  _globals['_STOREDELTA_OPERATION']._serialized_end=376
# @@protoc_insertion_point(module_scope)
