// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class FieldOptions {
  static encode(message: FieldOptions, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.loadFromFile);

    writer.uint32(16);
    writer.bool(message.zipFromFolder);
  }

  static decode(reader: Reader, length: i32): FieldOptions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new FieldOptions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.loadFromFile = reader.bool();
          break;

        case 2:
          message.zipFromFolder = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  loadFromFile: bool;
  zipFromFolder: bool;

  constructor(loadFromFile: bool = false, zipFromFolder: bool = false) {
    this.loadFromFile = loadFromFile;
    this.zipFromFolder = zipFromFolder;
  }
}
