// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class MsgVerifyInvariant {
  static encode(message: MsgVerifyInvariant, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    writer.uint32(18);
    writer.string(message.invariantModuleName);

    writer.uint32(26);
    writer.string(message.invariantRoute);
  }

  static decode(reader: Reader, length: i32): MsgVerifyInvariant {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgVerifyInvariant();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.invariantModuleName = reader.string();
          break;

        case 3:
          message.invariantRoute = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  invariantModuleName: string;
  invariantRoute: string;

  constructor(
    sender: string = "",
    invariantModuleName: string = "",
    invariantRoute: string = ""
  ) {
    this.sender = sender;
    this.invariantModuleName = invariantModuleName;
    this.invariantRoute = invariantRoute;
  }
}
